export const RegistrationDefaultValue = {
  supported_ages: "",
  cities_kenya: "",
  supported_years: "",
  sex_choices: "",
  participation: "",
  experience:"",
  hear_us:"",
  name: "",
  email:"",
  number: "",
  linkedin: "",
  overview: "",
  other_problems:"",
  healthcare_problem: "",
  software_stack: "",
  skill:"",
}
